### ISSUE TITLE
$ROOT not accessible in Build>command value

### ISSUE THREAD

**Issue by scorsi** [simplesurance/baur#152]
Hello,

I'm dealing with the following `.app.toml` :
```toml
name = "my-service"
[Build]
  command = "$ROOT/gradlew build"
  includes = []
  [Build.Input]
    [BuildInput.GitFiles]
      paths = ["$ROOT/build.gradle", "build.gradle", "src/**/*", "resources/**/*"]
  [Build.Output]
    [[Build.Output.File]]
      path = "build/libs/$APPNAME-dev-all.jar"
```
But it says `/gradlew no such file or directory`. The `$ROOT` variable is not injected.
I have to specify all the "../" for the pathname, it works but could be better. 

Btw, awesome projects 👍 

Thanks,
