### ISSUE TITLE
Add a BuildInput.Apps options

### ISSUE THREAD

**Issue by scorsi** [simplesurance/baur#154]
Hello,

It's could be cool to refer to another app without specifying its own used path. I think example is better than talking.
```toml
name = "my-service"
[Build]
  command = "..."
  [Build.Input]
    [BuildInput.GitFiles]
      paths = ["..."]
    [BuildInput.Apps]
      apps = ["shared"]
```
```toml
name = "shared"
[Build]
  command = "..."
  [Build.Input]
    [BuildInput.GitFiles]
      paths = ["..."]
```
So when the `BuildInput.GitFiles` of the `shared` project will change, it will build the `shared` app and after that `my-service` apps.

I'm not talking about managing dependencies, but look that feature like a trigger which `my-service` hook on the `shared` app. I don't know how easy it can be done in your codebase or if it can be done.

Thanks,
