### ISSUE TITLE
Add a on_completion_command option

### ISSUE THREAD

**Issue by scorsi** [simplesurance/baur#156]
Hello,

It could be nice to specify a command to execute once the `Build.Output` task has finished.

To explain a little bit why I need something like this, here my project/workflow example :

I have a mono-repo with all my different services of my application, all services dispose of a IaC in Terraform, to deploy new versions I need to notify Terraform Cloud to start the infrastructure migration (to deploy the new zip file or to make changes on the infrastructure). I have a CI/CD which manage all of this for me, from the building to the deploying.
So here the workflow: baur build -> gradle build -> baur output s3 file -> terraform plan/apply.

Maybe I can do that without a new task option ? Actually, I'm rebuilding all my services/infrastructures on any changes. Do you have any idea ?

Thanks,

**Comment by scorsi** [comment]
Maybe with something like:
```toml
name = "enrichment-service"
[Build]
  command = "gradle build"
  on_completion_command = "terraform apply -var=$DIST_FILE"
  includes = ["$ROOT/baur/gradle-service.toml"]
  [Build.Input]
    [Build.Input.GitFiles]
      paths = ["src/**/*", "resources/**/*"]
  [Build.Output]
    [[Build.Output.File]]
      path = "build/destinations/$APPNAME.zip"
      [Build.Output.File.S3Upload]
        dest_file = "/$APPNAME-$GITCOMMIT.zip"
```
The file is uploaded as `/$APPNAME-$GITCOMMIT.zip` to S3 and then if successfully pushed, `on_completion_command` is ran with `$DIST_FILE` parameter.
