### ISSUE TITLE
Support for multiple docker images to upload off a single build

### ISSUE THREAD

**Issue by akrock** [simplesurance/baur#217]
The goal would be to instead of having a single `idFile` property maybe have an array of `idFiles` that can be populated with more than 1 image that should be uploaded as result of a successful build.

Use case:

We have a projects that are micro worker deployments. A single project might have multiple workers that need to built into containers off the same source code and launched with different arguments.  In some cases different arguments have different requirements for base images which results in us needing to produce several unique docker images as an output of building 1 code base.

**Comment by fho** [comment]
if your build produces multiple docker images you can already specify multiple `[[BuildOutput.DockerImage]]` elements for each idFile, for example:

```toml
[BuildOutput]
    [[BuildOutput.DockerImage]]
      idfile = "image1.id"

      [BuildOutput.DockerImage.RegistryUpload]
        registry = "eu.gcr.io"
        repository = "docker/$APPNAME"
        tag = "image2-$GITCOMMIT"
 
    [[BuildOutput.DockerImage]]
      idfile = "image2.id"

      [BuildOutput.DockerImage.RegistryUpload]
        registry = "eu.gcr.io"
        repository = "docker/$APPNAME"
        tag = "image1-$GITCOMMIT"
```

Is that what you need? :-)
