### ISSUE TITLE
How to pass data from build script to `Task.Output.DockerImage.RegistryUpload`

### ISSUE THREAD

**Issue by kostyay** [simplesurance/baur#289]
Use case:
I have a build script that creates a docker image using docker build.
It decides the image tag/repo based on some parameters considered by the build script.

The docker output is configured in the following way:
```toml
        [[Task.Output.DockerImage.RegistryUpload]]

        # Registry address in the format <HOST>:[<PORT>]. If it's empty the docker agent's default is used.
        registry = ""
        repository = "{{ env DOCKER_IMAGE_REPOSITORY }}"
        tag = "{{ env DOCKER_IMAGE_TAG }}"
```

I need to somehow pass parameters into the `repository` and `tag` values as they are not constant and generated by the build script.
How can I do that? I tried setting env variables in the build script, but they are not passed down into the RegistryUpload step.

Thanks
