### ISSUE TITLE
Build.Input.Dockerfile or Build.Input.Docker-Compose

### ISSUE THREAD

**Issue by Puneeth-n** [simplesurance/baur#87]
It is more of an idea that I am jotting down here.

In our mono repo, We have dockerized all our services and lambdas. We use docker-compose to build our docker images. We prefer it over having building via `docker build ...` because the build details is machine readable.

With Build.Input.GitFiles or Build.Input.Files, I see that we need to maintain the truth at two different places; `Dockerfile` and `baur` file.

**Comment by fho** [comment]
I'm not sure If I understand the issue correctly.
Is the issue that you have to specify the path to the Dockerfile in the docker-compose config and in the baur config?

A way to realize what you want to do could be:
In baur you list your `Dockerfile`, the `docker-compose.yml` and all the application source files in the `Build.Input.Files` sections. This ensures that a rebuild is done when one of the file changes.

baur is relying on the `--iidfile` parameter of `docker build` to find the build image that it should upload to the docker-registry.
docker compose doesn't seem to support `--iidfile`, so you would have to workaround it.
A way to do that could be to use a script as build command.
The script calls `docker-compose build` and then afterwards writes the image id to a file.
The path to the file you specify in the `idfile` field in the `Build.Output.DockerImage` section of the `.app.toml` file.

**Comment by Puneeth-n** [comment]
@fho I was more thinking in the direction of, IFF baur read the `docker-compose.yml` to find all `Dockerfile`s and their `context`s to calculate  the `Build.Input.Files` instead of we specifying the `Build.Input.Files` configuration

**Comment by Puneeth-n** [comment]
Consider the following `docker-compose.yml`

```yaml
# vim: set ts=2 sw=2 sts=2 et :

version: '2.2'

services:
  addon:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CT_ECR: ${CT_ECR}
        CT_TAG: ${CT_TAG}
    image: ct-addon:${CT_TAG}
    environment:
      - NODE_ENV=test
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    command: tail -f /dev/null
```

Baur could potentially parse the `Dockerfile` and potentially see what all files are `COPY`ed or if `Dockerfile` itself changed or `docker-compose.yml` changed and dynamically generate the `Build.Input.Files`

With the current approach, I think we should manually specify under `Build.Input.Files` `Dockerfile`, `docker-compose.yml` and all files that are copied inside the docker image.
